FROM python:3.6-slim
RUN mkdir flower
COPY . flower/
WORKDIR flower/
ENV CELERY_BROKER_URL=redis://redis:6379
ENV CELERY_RESULT_BACKEND=redis://redis:6379

RUN cd package/
WORKDIR package
RUN pip install -r requirements.txt
WORKDIR flower/
CMD ["flower", "--B", "redis://redis:6379"]

